### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by koebi**
This is a starting point for an hungarian translation.

As @debyos stated in [his reply to his pull-request in the old app](https://github.com/GIScience/openrouteservice-app/pull/355#issuecomment-819845394), contributing a translation can seem overwhelming for anyone not familiar with programming.
Therefore, I took care of all things necessary and translation can now happen directly by editing all `*.i18n.hu-hu.js`-files in this pull request

Since the app switched from a monolithic to a component-based design, each component now has its own translation file.
Translations are not contained in one single, large file anymore, but split across many much smaller files.
There shouldn't be duplication, so overall the translation effort should basically stay the same.

### CODE REVIEW

**Comment by debyos** [comment]
Dear All,

thank you very much for you quick and thorough help in creating a start package for Hungarian translations. However, it's a shame but I can't go further either this way. I wanted to edit one of the three dozen files and it says that I had to "be on a branch" to be able to edit it. I am really sorry but I do not know how I could be on a branch (or even what it means)…

Nowadays, you can hear everywhere that to be successful you have to be able to code but this time I failed, even I dare to consider myself a power user - apparently, I am still a user and not a coder or administrator or whoever.

Thus, please give me some more instructions on how to proceed.

Sorry for the nuisance


Gábor

**Comment by amoncaldas** [comment]
I think that we should merge to develop only when the translation is done. I think it will now be easier to contribute withe language translations after the changes I have made. Please check this https://github.com/GIScience/ors-map-client/issues/124#issuecomment-821043350 and this https://github.com/GIScience/ors-map-client#--generate-a-translation-file

**Comment by debyos** [comment]
Thank you, the [merged file](https://github.com/GIScience/ors-map-client/blob/develop/docs/en-translation-source-merged.json) is fine. I have already started to translate it, hopefully, I can finish it in some days.

**Comment by debyos** [comment]
And I already have some questions: is the maximum surface of an avoidable polygon 
- 20.000 square km or ([line 166](https://github.com/GIScience/ors-map-client/blob/develop/docs/en-translation-source-merged.json))
- 200.000 square km ([line 261](https://github.com/GIScience/ors-map-client/blob/develop/docs/en-translation-source-merged.json))?

And in
```
      "length": {
        "label": "Length",
        "description": "The maximum length in meters"
```
Is **meters** correct? Should it be **kilometres**?

**Comment by debyos** [comment]
And then `…some avoidables have limits, like the route lenght and the area of an avoid polygon that must not exceed 200000 square kilometers`

First, length (instead of lenght) would look better.

Then it is a bit unclear how this sentence should be understood. Are _avoidables_ things to be avoided? 
That is
- a thing to be avoided may be a route (whose length is limited to something) and 
- another thing to be avoided may be a polygon (whose area is limited to 200.000 (or 20.000) sq km)?

**Comment by amoncaldas** [comment]
Hey @debyos 
thanks for reporting the typos (lenght and 200000 square km). I have already created a issue for this. I will fix it very soon. https://github.com/GIScience/ors-map-client/issues/126

Answering your questions:

Are avoidables things to be avoided? -> yes, avoidables are things to be avoided, like Ferries, Fords, Steps or even a Polygon drawn by the user.
When planning a route the user can define things to be avoided (avoidables) so that a route that does not pass through them. When one or more avoidables are defined, the route length has a limit and also the the polygon (if present) can not have more then 20000 square km.

**Comment by debyos** [comment]
Dear @amoncaldas,

thank you for the responsiveness! I have yet another, easy, question: [in line 256](https://github.com/GIScience/ors-map-client/blob/develop/docs/en-translation-source-merged.json) there is `"for"`. 
Being so alone, it can have several meanings in Hungarian (and, I suppose, also in other languages).
Thus could you give me some clue of its context or a screenshot or whatever?

Cheers

Gábor

**Comment by amoncaldas** [comment]
Dear @debyos 
It seems it is a garbage left by accident. I have already removed it locally, so it will not be present in the next deploy. You can just ignore this "for".

**Comment by debyos** [comment]
Dear @amoncaldas,
thanks for the prompt answer. Then another question [in line 392](https://github.com/GIScience/ors-map-client/blob/develop/docs/en-translation-source-merged.json):

`Convert stop after route ending to destination`

What does this mean in a bit more explicit way? Maybe something like 
_After route ending, convert stop to destination_?
Nevertheless, it continues to be unclear, at least for me.

Thanks
_Gábor_

**Comment by amoncaldas** [comment]
Hey @debyos 
Please read the thread below and hopefully you will understand it. The final message is still valid.

https://github.com/GIScience/ors-map-client/issues/101

**Comment by debyos** [comment]
Hi @amoncaldas,
thank you, I am already a lot wiser and could produce a fine translation.

[In line 489](https://github.com/GIScience/ors-map-client/blob/develop/docs/en-translation-source-merged.json) there is `highlighting`
Who highlights what?
Since it does not begin with a capital letter I suppose it is inside a sentence, probably somehow by polygons to be avoided but I can't find it on the front end site.
Bye

Gábor

**Comment by amoncaldas** [comment]
Hey @debyos 
Just to let you know: I've updated the merged English translation source file with the following changes:
Added `useStopOptimization` key
Rephrased "Convert stop after route ending to destination" to "Convert stop added at the end of the route to final destination"

**Comment by amoncaldas** [comment]
@debyos 

Please see my comments below.

In line 489 there is highlighting. Who highlights what? -> a sentence like this will be built: "Highlighting way category:" where `way category` is populated dynamically (but also using a translation key) 

Then there are signs that might appear code but I don't know whether they are indeed:
click on \"my location\" button -> this is just to escape the quote character, because we want to display, in this case, the quotes in the presented text, like "my location". 

Then, among the map filters there are some pieces where I would request some clarification:

    "delivery": "Delivery truck", – This might be a delivery truck
    "goods": "Goods truck" – This might be a smaller truck

The big question is what is the difference between the two above? -> If I remember it correctly, goods truck is the big used to transport things across regions/countries an and delivery truck is the smaller one that go through the city to delivery something.

**Comment by debyos** [comment]
Dear @amoncaldas,
thank you for the many clarifications. I would have some more questions:

## Extra Info
### Generally
What is the difference between _way types_ and _way categories_?
### Specifically
**Way types**: what is the difference between _state road_, _road_ and _street_?
For example
- state roads [tagged](https://wiki.openstreetmap.org/wiki/Key:highway) as : `motorway`, `trunk`
- roads: `primary`, `secondary` etc. 
- streets: `residential`, `living_street` etc.?

**Way category**
What are _highways_, in this specific case?

The rendering is slightly obscure, e.g. [in this case](https://maps.openrouteservice.org/#/directions/D%C3%A1ni%20utca,Szegedin,Hungary/Nesz%C3%BCrjhegyi%20kertsor,Hungary/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,38,0,24,3,160,17,128,22,124,6,103,212,129,88,7,96,19,129,195,76,46,242,1,167,32,54,99,241,211,110,73,181,102,229,74,240,13,196,88,161,90,116,0,113,53,47,129,162,245,204,123,242,165,87,188,242,26,54,212,50,11,136,8,0,29,83,192,136,155,14,80,151,160,64,6,111,0,13,186,92,33,99,71,128,6,228,128,14,96,11,70,12,141,6,98,0,5,229,0,11,107,138,72,160,11,226,148,0) there are almost no highways whereas there should be kilometres of steps which is not the case in real life.

**Comment by debyos** [comment]
Dear @amoncaldas,

now I am ready.

After you answered the last questions above, I can post here my translation (which considers also the [your updates mentioned above](https://github.com/GIScience/ors-map-client/pull/123#issuecomment-823889227)).

Bye

_Gábor_

**Comment by amoncaldas** [comment]
@debyos 

What is the difference between way types and way categories? -> this is a more semantic information that I'm afraid I will not be able to tell you in details. They are classifications of OSM. Be aware that OSM is a crowdsourcing project and not all tags and classifications are planned in a centralized way. So redundancies and overlappings may occur. 

Way types: what is the difference between state road, road and street? -> `state road` is a road that is under the responsibility of a state (specially for countries that have states, like US, Brazil etc). `Road` is a road that has not other information (like if it federal or state road). For `street` this page https://www.differencebetween.com/difference-between-road-and-street/ might help you.
For example

    state roads tagged as : motorway, trunk
    roads: primary, secondary etc.
    streets: residential, living_street etc.?

Way category
What are highways, in this specific case? -> sorry, I didn't get your point here. Isn't it just a highway?

Suitability
What is this? I couldn't get it appear on the front-end… -> how suitable a way is for a given profile and filters. For example, a cyclist might take a road, but if it is a bike-road, it will be considered more suitable.

**Comment by debyos** [comment]
Dear @amoncaldas,

thanks for the answers. (I hope I do not annoy you very much.)

As for Way types & Way categroies I just thought that they are based on various OSM taggings. Since I am quite familiar with OSM (including tags), it would have helped me if I know that a given Way type or Way category corresponds to certain tags (of combination of tags). If it is more complicated than that, then I will just leave as it is.

As for highway I wanted to ask wether that is meant:
- a public road, mainly in the countryside ([official and UK meaning](https://en.wikipedia.org/wiki/Highway))
- a major road ([US meaning](https://en.wikipedia.org/wiki/Highway#United_States)) or
- any possible road, street, path etc. ([OSM meaning](https://wiki.openstreetmap.org/wiki/Key:highway))

Best wishes


_Gábor_

**Pull request merged**
